#!/bin/sh

DAEMON="/usr/bin/aesdsocket"
NAME="aesdsocket"

case "$1" in
    start)
        echo "Starting $NAME..."
        start-stop-daemon -S -n $NAME -a $DAEMON -- -d
        ;;
    stop)
        echo "Stopping $NAME..."
        start-stop-daemon -K -n $NAME -s SIGTERM
        ;;
    restart|reload)
        "$0" stop
        sleep 1
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
